export const PROMPT_CHAT_REQUEST = "PROMPT_CHAT_REQUEST";
export const PROMPT_CHAT_SUCCESS = "PROMPT_CHAT_SUCCESS";

export const REQUEST_CHAT_HISTORY = "REQUEST_CHAT_HISTORY";
export const CHAT_HISTORY = "CHAT_HISTORY";

export const REQUEST_DELETE_HISTORY = "REQUEST_DELETE_HISTORY";

export const REQUEST_CHATID_DATA = "REQUEST_CHATID_DATA";
export const CHATID_DATA = "CHATID_DATA";
export const NEW_CHAT = "NEW_CHAT";
export const REQUEST_GROUPCHAT = "REQUEST_GROUPCHAT";
export const SHOW_TYPING_INDICATOR = "SHOW_TYPING_INDICATOR";
export const HIDE_TYPING_INDICATOR = "HIDE_TYPING_INDICATOR";
export const LOADING = 'LOADING';
export const REQUEST_REMOVEEXPERT = 'REQUEST_REMOVEEXPERT';
export const NEW_CHAT_IDS = 'NEW_CHAT_IDS';
