export const REQUEST_GET_APPLICATION = "REQUEST_GET_APPLICATION";
export const GET_APPLICATION = "GET_APPLICATION";
export const REQUEST_GET_TAGS = "REQUEST_GET_TAGS";
export const GET_TAGS = "GET_TAGS";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const DELETE_APPLICATION = "DELETE_APPLICATION";
