version: 2
updates:
  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer1"  # Replace with actual maintainer usernames
    assignees:
      - "maintainer1"  # Replace with actual maintainer usernames

  # Enable version updates for pip (backend)
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer1"  # Replace with actual maintainer usernames
    assignees:
      - "maintainer1"  # Replace with actual maintainer usernames

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5 