version: '3.8'

services:
  open-copilot-mongo:
    image: mongo:latest
    container_name: open-copilot-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./workspace/open-copilot-mongo/mongo-db:/data/db
      - ./workspace/open-copilot-mongo/logs:/var/log/mongodb

  open-copilot-opensearch:
    image: opensearchproject/opensearch:latest
    container_name: open-copilot-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.authcz.admin_dn=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./workspace/open-copilot-opensearch/indexes:/usr/share/opensearch/data
      - ./workspace/open-copilot-opensearch/logs:/usr/share/opensearch/logs
    ports:
      - "9200:9200"
      - "9600:9600"

  open-copilot-neo4j:
    image: neo4j:latest
    container_name: open-copilot-neo4j
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - "7883:7687"
      - "7474:7474"
    volumes:
      - ./workspace/open-copilot-neo4j/data:/data
      - ./workspace/open-copilot-neo4j/logs:/logs

  open-copilot-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: open-copilot-web
    ports:
      - "5471:5471"
    environment:
      - PORT=5471
    volumes:
      - ./workspace/open-copilot-web/user-files:/app/public
      - ./workspace/open-copilot-web/logs:/var/log/web
    depends_on:
      - open-copilot-api

  open-copilot-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: open-copilot-api
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - MODE=private
      - PRIVATE_BASE_URL=${PRIVATE_BASE_URL}
      - PRIVATE_SECRET_KEY=${PRIVATE_SECRET_KEY}
      - PRIVATE_MODEL=${PRIVATE_MODEL}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - K=${K}
    volumes:
      - ./workspace/open-copilot-api/logs:/var/log/api
    depends_on:
      - open-copilot-mongo
      - open-copilot-opensearch
      - open-copilot-neo4j
