export const VALID_TOKEN = "VALID_TOKEN";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RETRIEVE_USER_REQUEST = "RETRIEVE_USER_REQUEST";
export const RETRIEVE_USER_SUCCESS = "RETRIEVE_USER_SUCCESS";
export const LOG_OUT = "LOG_OUT";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const RETRIEVE_USERS_SUCCESS = "RETRIEVE_USERS_SUCCESS";
export const RETRIEVE_DELETE_USER = "RETRIEVE_DELETE_USER";
export const RETRIEVE_EDIT_USER = "RETRIEVE_EDIT_USER";

export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const SUCCESS = "SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

export const REQUEST_RESET_PASSWORD = "REQUEST_RESET_PASSWORD";

export const CREATE_APIKEY_REQUEST = "CREATE_APIKEY_REQUEST";
export const GET_APIKEY_REQUEST = "GET_APIKEY_REQUEST";
export const GET_API_KEY = "GET_API_KEY";
export const DELETE_API_KEY = "DELETE_API_KEY";

export const GET_CONFIGS_DETAILS = "GET_CONFIGS_DETAILS";
export const UPDATE_CONFIGS_DETAILS = "UPDATE_CONFIGS_DETAILS";
export const UPDATE_SYSTEM_CONTROLS = "UPDATE_SYSTEM_CONTROLS";